"""
Flask-based viewer for AgentFlow YAML artifacts generated by the CLI.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml
from flask import Flask, abort, jsonify, render_template_string, send_from_directory


@dataclass
class PlanArtifact:
    plan_id: str
    name: str
    status: str
    filename: str
    created_at: Optional[str]
    last_updated: Optional[str]
    path: Path


INDEX_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>AgentFlow Plans</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 2rem; background: #f7f7f7; color: #333; }
    h1 { margin-bottom: 1rem; }
    table { border-collapse: collapse; width: 100%; background: #fff; }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f0f0f0; }
    tr:hover { background: #f5f5f5; }
    code { background: #eee; padding: 0.15rem 0.3rem; border-radius: 4px; }
    .status-badge { padding: 0.25rem 0.5rem; border-radius: 1rem; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; }
    .status-completed { background: #d4f4dd; color: #1b6b3a; }
    .status-failed { background: #f8d7da; color: #842029; }
    .status-other { background: #dbeafe; color: #1d4ed8; }
    .footer { margin-top: 2rem; font-size: 0.85rem; color: #666; }
    .empty { padding: 2rem; background: #fff; text-align: center; border: 1px dashed #ccc; }
  </style>
</head>
<body>
  <h1>AgentFlow Plans</h1>
  {% if plans %}
  <table>
    <thead>
      <tr>
        <th>Plan</th>
        <th>Status</th>
        <th>Created</th>
        <th>Updated</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for plan in plans %}
      <tr>
        <td>
          <strong>{{ plan.name }}</strong><br>
          <code>{{ plan.plan_id }}</code><br>
          <small>{{ plan.filename }}</small>
        </td>
        <td>
          <span class="status-badge {{ plan.status_class }}">{{ plan.status }}</span>
        </td>
        <td>{{ plan.created_at or "—" }}</td>
        <td>{{ plan.last_updated or "—" }}</td>
        <td>
          <a href="/plans/{{ plan.plan_id }}">View JSON</a> |
          <a href="/files/{{ plan.filename }}">Download YAML</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <div class="empty">
      <p>No AgentFlow plan artifacts found.</p>
      <p>Run <code>agentflow "your prompt"</code> to create one.</p>
    </div>
  {% endif %}
  <div class="footer">
    Serving directory: <code>{{ root_directory }}</code>
  </div>
</body>
</html>
"""


def run_viewer(*, directory: Path, host: str, port: int) -> None:
    app = _create_app(directory)
    app.run(host=host, port=port, debug=False, use_reloader=False)


def _create_app(root: Path) -> Flask:
    app = Flask(__name__)

    @app.route("/")
    def index():
        plans = [_serialize_summary(artifact) for artifact in _discover_plans(root)]
        return render_template_string(INDEX_TEMPLATE, plans=plans, root_directory=str(root))

    @app.route("/plans")
    def list_plans():
        summaries = [_summary_payload(artifact) for artifact in _discover_plans(root)]
        return jsonify(summaries)

    @app.route("/plans/<plan_id>")
    def view_plan(plan_id: str):
        artifact = _find_plan(root, plan_id)
        if not artifact:
            abort(404, description=f"Plan {plan_id} not found.")
        payload = _load_payload(artifact.path)
        return jsonify(payload)

    @app.route("/files/<path:filename>")
    def download_file(filename: str):
        target = (root / filename).resolve()
        if not str(target).startswith(str(root.resolve())):
            abort(403)
        if not target.exists():
            abort(404)
        return send_from_directory(root, filename)

    return app


def _discover_plans(root: Path) -> List[PlanArtifact]:
    artifacts: List[PlanArtifact] = []
    for path in sorted(root.glob("agentflow-*.yaml")):
        try:
            payload = _load_payload(path)
        except Exception:
            continue

        if not isinstance(payload, dict):
            continue
        plan_id = payload.get("plan_id")
        if not plan_id:
            continue
        schema_version = payload.get("schema_version")
        if schema_version != "1.0":
            continue

        artifact = PlanArtifact(
            plan_id=plan_id,
            name=payload.get("name", plan_id),
            status=payload.get("status", "unknown"),
            filename=path.name,
            created_at=payload.get("created_at"),
            last_updated=payload.get("last_updated"),
            path=path,
        )
        artifacts.append(artifact)
    return artifacts


def _find_plan(root: Path, plan_id: str) -> Optional[PlanArtifact]:
    for artifact in _discover_plans(root):
        if artifact.plan_id == plan_id:
            return artifact
    return None


def _load_payload(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError("Invalid plan structure.")
    return data


def _summary_payload(artifact: PlanArtifact) -> Dict[str, Any]:
    return {
        "plan_id": artifact.plan_id,
        "name": artifact.name,
        "status": artifact.status,
        "filename": artifact.filename,
        "created_at": artifact.created_at,
        "last_updated": artifact.last_updated,
    }


def _serialize_summary(artifact: PlanArtifact) -> Dict[str, Any]:
    status = artifact.status or "unknown"
    status_class = "status-other"
    if status == "completed":
        status_class = "status-completed"
    elif status == "failed":
        status_class = "status-failed"

    return {
        "plan_id": artifact.plan_id,
        "name": artifact.name,
        "status": status,
        "status_class": status_class,
        "filename": artifact.filename,
        "created_at": artifact.created_at,
        "last_updated": artifact.last_updated,
    }
